export const TYPES = {
    ADD_TO_CART: "AGREGAR_A_CARRITO",
    REMOVE_ONE_FROM_CART: "RBORRAR_DEL_CARRITO",
    REMOVE_ALL_FROM_CART: "BORRAR_TODO_EL_CARRITO",
    CLEAR_CART: "BORRAR_CARRITO",



}